
server:
  port: 7788

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/estimaai
    username: root
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


estimaai:
  ignored-path: >
    /,
    /csrf,
    /error,
    /login,
    /test/**,
    /static/**,
    /public/**,
    /swagger**/**,
    /.well-known/**,
    /v2/api-docs/**,
    /v3/api-docs/**,
    favicon.ico
